mv ./share/pixmaps/vrontonode16.png ./share/pixmaps/lkrm16.png
mv ./share/pixmaps/vrontonode128.png ./share/pixmaps/lkrm128.png
mv ./share/pixmaps/vrontonode256.png ./share/pixmaps/lkrm256.png
mv ./share/pixmaps/vrontonode64.png ./share/pixmaps/lkrm64.png
mv ./share/pixmaps/vrontonode64.xpm ./share/pixmaps/lkrm64.xpm
mv ./share/pixmaps/vrontonode32.xpm ./share/pixmaps/lkrm32.xpm
mv ./share/pixmaps/vrontonode256.xpm ./share/pixmaps/lkrm256.xpm
mv ./share/pixmaps/vrontonode32.png ./share/pixmaps/lkrm32.png
mv ./share/pixmaps/vrontonode128.xpm ./share/pixmaps/lkrm128.xpm
mv ./share/pixmaps/vrontonode.ico ./share/pixmaps/lkrm.ico
mv ./share/pixmaps/vrontonode16.xpm ./share/pixmaps/lkrm16.xpm
mv ./src/config/vrontonode-config.h.in~ ./src/config/lkrm-config.h.in~
mv ./src/config/vrontonode-config.h.in ./src/config/lkrm-config.h.in
mv ./src/vrontonode-tx.cpp ./src/lkrm-tx.cpp
mv ./src/vrontonoded.cpp ./src/lkrmd.cpp
mv ./src/vrontonoded-res.rc ./src/lkrmd-res.rc
mv ./src/vrontonode-cli-res.rc ./src/lkrm-cli-res.rc
mv ./src/test/test_vrontonode.cpp ./src/test/test_lkrm.cpp
mv ./src/qt/vrontonode.cpp ./src/qt/lkrm.cpp
mv ./src/qt/res/icons/vrontonode_testnet.ico ./src/qt/res/icons/lkrm_testnet.ico
mv ./src/qt/res/icons/vrontonode.icns ./src/qt/res/icons/lkrm.icns
mv ./src/qt/res/icons/vrontonode.png ./src/qt/res/icons/lkrm.png
mv ./src/qt/res/icons/vrontonode.ico ./src/qt/res/icons/lkrm.ico
mv ./src/qt/res/icons/vrontonode_testnet.png ./src/qt/res/icons/lkrm_testnet.png
mv ./src/qt/res/vrontonode-qt-res.rc ./src/qt/res/lkrm-qt-res.rc
mv ./src/qt/res/fonts/vrontonode_font.ori.ttf ./src/qt/res/fonts/lkrm_font.ori.ttf
mv ./src/qt/res/fonts/vrontonode_font.ttf ./src/qt/res/fonts/lkrm_font.ttf
mv ./src/qt/res/images/vrontonode_logo_horizontal.png ./src/qt/res/images/lkrm_logo_horizontal.png
mv ./src/qt/locale/vrontonode_sv.ts ./src/qt/locale/lkrm_sv.ts
mv ./src/qt/locale/vrontonode_es.ts ./src/qt/locale/lkrm_es.ts
mv ./src/qt/locale/vrontonode_ru.ts ./src/qt/locale/lkrm_ru.ts
mv ./src/qt/locale/vrontonode_cs.ts ./src/qt/locale/lkrm_cs.ts
mv ./src/qt/locale/vrontonode_sk.ts ./src/qt/locale/lkrm_sk.ts
mv ./src/qt/locale/vrontonode_ja.ts ./src/qt/locale/lkrm_ja.ts
mv ./src/qt/locale/vrontonode_bg.ts ./src/qt/locale/lkrm_bg.ts
mv ./src/qt/locale/vrontonode_da.ts ./src/qt/locale/lkrm_da.ts
mv ./src/qt/locale/vrontonode_fr_FR.ts ./src/qt/locale/lkrm_fr_FR.ts
mv ./src/qt/locale/vrontonode_pt.ts ./src/qt/locale/lkrm_pt.ts
mv ./src/qt/locale/vrontonode_en_US.ts ./src/qt/locale/lkrm_en_US.ts
mv ./src/qt/locale/vrontonode_ro_RO.ts ./src/qt/locale/lkrm_ro_RO.ts
mv ./src/qt/locale/vrontonode_zh_TW.ts ./src/qt/locale/lkrm_zh_TW.ts
mv ./src/qt/locale/vrontonode_ca.ts ./src/qt/locale/lkrm_ca.ts
mv ./src/qt/locale/vrontonode_tr.ts ./src/qt/locale/lkrm_tr.ts
mv ./src/qt/locale/vrontonode_it.ts ./src/qt/locale/lkrm_it.ts
mv ./src/qt/locale/vrontonode_ko_KR.ts ./src/qt/locale/lkrm_ko_KR.ts
mv ./src/qt/locale/vrontonode_pt_BR.ts ./src/qt/locale/lkrm_pt_BR.ts
mv ./src/qt/locale/vrontonode_pl.ts ./src/qt/locale/lkrm_pl.ts
mv ./src/qt/locale/vrontonode_nl.ts ./src/qt/locale/lkrm_nl.ts
mv ./src/qt/locale/vrontonode_uk.ts ./src/qt/locale/lkrm_uk.ts
mv ./src/qt/locale/vrontonode_zh_CN.ts ./src/qt/locale/lkrm_zh_CN.ts
mv ./src/qt/locale/vrontonode_fi.ts ./src/qt/locale/lkrm_fi.ts
mv ./src/qt/locale/vrontonode_de.ts ./src/qt/locale/lkrm_de.ts
mv ./src/qt/locale/vrontonode_en.ts ./src/qt/locale/lkrm_en.ts
mv ./src/qt/vrontonode.qrc ./src/qt/lkrm.qrc
mv ./src/qt/vrontonodestrings.cpp ./src/qt/lkrmstrings.cpp
mv ./src/qt/vrontonode_locale.qrc ./src/qt/lkrm_locale.qrc
mv ./src/vrontonode-cli.cpp ./src/lkrm-cli.cpp
mv ./contrib/debian/vrontonoded.manpages ./contrib/debian/lkrmd.manpages
mv ./contrib/debian/vrontonoded.bash-completion ./contrib/debian/lkrmd.bash-completion
mv ./contrib/debian/vrontonode-qt.install ./contrib/debian/lkrm-qt.install
mv ./contrib/debian/vrontonode-qt.protocol ./contrib/debian/lkrm-qt.protocol
mv ./contrib/debian/vrontonode-qt.desktop.desktop.desktop ./contrib/debian/lkrm-qt.desktop.desktop.desktop
mv ./contrib/debian/vrontonoded.install ./contrib/debian/lkrmd.install
mv ./contrib/debian/examples/vrontonode.conf ./contrib/debian/examples/lkrm.conf
mv ./contrib/debian/vrontonoded.examples ./contrib/debian/lkrmd.examples
mv ./contrib/debian/vrontonode-qt.lintian-overrides ./contrib/debian/lkrm-qt.lintian-overrides
mv ./contrib/debian/vrontonoded.lintian-overrides ./contrib/debian/lkrmd.lintian-overrides
mv ./contrib/vrontonode-qt.pro ./contrib/lkrm-qt.pro
mv ./contrib/vrontonoded.bash-completion ./contrib/lkrmd.bash-completion
mv ./contrib/init/vrontonoded.openrc ./contrib/init/lkrmd.openrc
mv ./contrib/init/vrontonoded.service ./contrib/init/lkrmd.service
mv ./contrib/init/vrontonoded.openrcconf ./contrib/init/lkrmd.openrcconf
mv ./contrib/init/vrontonoded.conf ./contrib/init/lkrmd.conf
mv ./contrib/init/vrontonoded.init ./contrib/init/lkrmd.init

